ALTER TABLE my_user
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE my_course
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE my_department
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE my_class
    ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
