spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/stumanage?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 2

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
